#ifndef ESSCONTROLLER_GLOBAL_H
#define ESSCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ESSCONTROLLER_LIBRARY)
#  define ESSCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ESSCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ESSCONTROLLER_GLOBAL_H
